version: '3.8'

networks:
  capstone-network:
    driver: bridge

services:
  # ==========================================
  # 1. INFRASTRUCTURE & DISCOVERY
  # ==========================================
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: abhinavraj
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: capstone_db # Shared DB for simplicity
    ports:
      - "5432:5432"
    networks:
      - capstone-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d microservices_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/app/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS=file:/app/config-repo
    networks:
      - capstone-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config-server
    networks:
      - capstone-network

  # ==========================================
  # 2. BUSINESS MICROSERVICES
  # ==========================================
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/capstone_db
      - SPRING_DATASOURCE_USERNAME=abhinavraj
      - SPRING_DATASOURCE_PASSWORD=""
    depends_on:
      postgres-db:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - capstone-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/capstone_db
      - SPRING_DATASOURCE_USERNAME=abhinavraj
      - SPRING_DATASOURCE_PASSWORD="
    depends_on:
      postgres-db:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - capstone-network

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/capstone_db
      - SPRING_DATASOURCE_USERNAME=abhinavraj
      - SPRING_DATASOURCE_PASSWORD=""
    depends_on:
      postgres-db:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - capstone-network

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/capstone_db
      - SPRING_DATASOURCE_USERNAME=abhinavraj
      - SPRING_DATASOURCE_PASSWORD=""
    depends_on:
      postgres-db:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - capstone-network

  management-service:
    build: ./management-service
    container_name: management-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/capstone_db
      - SPRING_DATASOURCE_USERNAME=abhinavraj
      - SPRING_DATASOURCE_PASSWORD=""
    depends_on:
      postgres-db:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - capstone-network

  # ==========================================
  # 3. API GATEWAY (The Entry Point)
  # ==========================================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - config-server
      - eureka-server
      - auth-service
      - user-service
      - product-service
      - inventory-service
      - management-service
    networks:
      - capstone-network